import type { NextPage } from 'next';
import Head from 'next/head';
import { PostCard } from '../components/PostCard/PostCard';
import { Typo } from '../components/Elements/Typo/Typo';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <Typo role='display-medium' style={{ fontWeight: '700' }}>
          All Posts
        </Typo>
        <div>divider</div>
        <div>드롭다운: 태그, 최신순</div>
        <PostCard />
      </div>
    </>
  );
};

export default Home;
