export type IconRoleUnionType =
	| 'github'
	| 'twitter'
	| 'linkedIn'
	| 'email'
	| 'menu-fold'
	| 'menu-unfold'
	| 'about'
	| 'html'
	| 'css'
	| 'javascript'
	| 'typescript'
	| 'react'
	| 'graphql'
	| 'about'
	| 'search'
	| 'home'
	| 'dropdown'
	| 'forward';

export type TypoRoleUnionType =
	| 'display-large'
	| 'display-medium'
	| 'display-small'
	| 'headline-large'
	| 'headline-medium'
	| 'headline-small'
	| 'title-large'
	| 'title-medium'
	| 'title-small'
	| 'label-large'
	| 'label-medium'
	| 'label-small'
	| 'body-large'
	| 'body-medium'
	| 'body-small';
